---
version: 2.1

jobs:
  mariadb:
    docker:
    - image: circleci/golang:1.15
      environment:
        SQL_DRIVER: mysql
        DB_URI: versions:versions@tcp(127.0.0.1:3306)/versions?charset=utf8&autocommit=true&multiStatements=true&maxAllowedPacket=0&interpolateParams=true
    - image: mariadb:10.5
      environment:
        MYSQL_DATABASE: versions
        MYSQL_USER: versions
        MYSQL_PASSWORD: versions
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"

    steps:
    # pull sources
    - checkout

    - run:
        name: Wait for DB to be ready
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

    - run:
        name: Perform unit testing
        command: go test -v

  postgres:
    docker:
    - image: circleci/golang:1.15
      environment:
        SQL_DRIVER: postgres
        DB_URI: postgres://versions:versions@127.0.0.1:5432/versions?sslmode=disable
    - image: postgres:13.1
      environment:
        POSTGRES_DB: versions
        POSTGRES_USER: versions
        POSTGRES_PASSWORD: versions

    steps:
    # pull sources
    - checkout

    - run:
        name: Wait for DB to be ready
        command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m

    - run:
        name: Perform unit testing
        command: go test -v

  build-image:
    docker:
    - image: golang:1.15-alpine

    steps:
    # pull sources
    - checkout

    - run:
        name: Try to build docker image
        command: docker build -t versions-api:latest .

workflows:
  version: 2
  test-and-build:
    jobs:
    - mariadb
    - postgres
    - build-image:
        requires:
        - mariadb
        - postgres